<?php
/**
 * Copyright © 2026
 * @category Null
 * @package Null_Blueprint
 * @author Ivan Miskic
 * @license http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
declare(strict_types=1);

/** @var \Null\Blueprint\Block\Widget\CampaignProducts $block */
/** @var \Magento\Framework\Escaper $escaper */
?>
<?php if ($block->isEmpty()): ?>
    <?= /* @noEscape */ $block->fetchView($block->getTemplateFile('Null_Blueprint::widget/campaign/empty.phtml')) ?>
<?php else: ?>
    <div class="block widget block-products-list blueprint-widget blueprint-widget--grid">
        <?php if ($block->getTitle()): ?>
            <div class="block-title">
                <strong><?= $escaper->escapeHtml($block->getTitle()) ?></strong>
            </div>
        <?php endif; ?>
        <div class="block-content">
            <div class="products-grid grid">
                <ol class="product-items">
                    <?php foreach ($block->getProductCollection() as $product): ?>
                        <li class="product-item">
                            <a class="product-item-link"
                               href="<?= $escaper->escapeUrl($product->getProductUrl()) ?>"
                               title="<?= $escaper->escapeHtmlAttr($product->getName()) ?>">
                                <?= /* @noEscape */ $block->getImage($product, 'new_products_content_widget_grid')->toHtml() ?>
                                <span class="product-item-name"><?= $escaper->escapeHtml($product->getName()) ?></span>
                            </a>
                            <?= /* @noEscape */ $block->getProductPriceHtml($product, 'widget-new-grid') ?>
                        </li>
                    <?php endforeach; ?>
                </ol>
            </div>
            <?= /* @noEscape */ $block->getPagerHtml() ?>
        </div>
    </div>
<?php endif; ?>
